# Generated by Django 4.2 on 2023-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_date', models.DateField()),
                ('donation_type', models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient')], max_length=20)),
                ('donor_name', models.CharField(max_length=255)),
            ],
        ),
    ]
