# Generated by Django 4.2 on 2023-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationtransaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransaction',
            name='donation_date',
            field=models.DateTimeField(),
        ),
    ]
