# Generated by Django 4.2 on 2023-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationtransaction', '0002_alter_donationtransaction_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtransaction',
            name='purpose',
            field=models.CharField(choices=[('education', 'Education Support'), ('flood_relief', 'Flood Relief'), ('empowering_live', 'Empowering Live'), ('tuition_program', 'Tuition Program')], default='education', max_length=20),
            preserve_default=False,
        ),
    ]
