# Generated by Django 4.2 on 2023-05-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
    ]
