# Generated by Django 4.2 on 2023-05-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationrequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequest',
            old_name='data',
            new_name='date',
        ),
    ]
